# Generated by Django 2.2.6 on 2020-01-07 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bankName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Bank'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ifscNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
